version: '3.8'

services:
  mestre:
    build: ./mestre
    ports:
      - "8000:8000"
    depends_on:
      - escravo-letras
      - escravo-numeros

  escravo-letras:
    build: ./escravo-letras
    ports:
      - "8001:8001"

  escravo-numeros:
    build: ./escravo-numeros
    ports:
      - "8002:8002"
